[package]
name = "soccer"
version = "0.1.0"
authors = ["Julien Blanchard <julien@sideburns.eu>"]

[dependencies]
hyper = "0.12"
serde = "*"
serde_derive = "*"
serde_json = "*"
chrono = "0.4"
deunicode = "0.4.0"